// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TASKGRAPH_FLATBUFTASKGRAPH_H_
#define FLATBUFFERS_GENERATED_TASKGRAPH_FLATBUFTASKGRAPH_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
// static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
//               FLATBUFFERS_VERSION_MINOR == 3 &&
//               FLATBUFFERS_VERSION_REVISION == 25,
//              "Non-compatible flatbuffers version included");

namespace FlatBufTaskGraph {

struct Task;
struct TaskBuilder;

struct Device;
struct DeviceBuilder;

struct Operator;
struct OperatorBuilder;

struct TaskGraph;
struct TaskGraphBuilder;

enum SimTaskType : int16_t {
  SimTaskType_TASK_FORWARD = 0,
  SimTaskType_TASK_BACKWARD = 1,
  SimTaskType_TASK_COMM = 2,
  SimTaskType_TASK_UPDATE = 3,
  SimTaskType_TASK_BARRIER = 4,
  SimTaskType_TASK_NOMINAL_COMM = 5,
  SimTaskType_TASK_P2P = 6,
  SimTaskType_TASK_SUB_ALLREDUCE = 7,
  SimTaskType_TASK_DP_ALLREDUCE = 8,
  SimTaskType_TASK_TP_ALLREDUCE = 9,
  SimTaskType_TASK_ALLREDUCE = 10,
  SimTaskType_TASK_REDUCESCATTER = 11,
  SimTaskType_TASK_ALLGATHER = 12,
  SimTaskType_TASK_ALLTOALL = 13,
  SimTaskType_MIN = SimTaskType_TASK_FORWARD,
  SimTaskType_MAX = SimTaskType_TASK_ALLTOALL
};

inline const SimTaskType (&EnumValuesSimTaskType())[14] {
  static const SimTaskType values[] = {
    SimTaskType_TASK_FORWARD,
    SimTaskType_TASK_BACKWARD,
    SimTaskType_TASK_COMM,
    SimTaskType_TASK_UPDATE,
    SimTaskType_TASK_BARRIER,
    SimTaskType_TASK_NOMINAL_COMM,
    SimTaskType_TASK_P2P,
    SimTaskType_TASK_SUB_ALLREDUCE,
    SimTaskType_TASK_DP_ALLREDUCE,
    SimTaskType_TASK_TP_ALLREDUCE,
    SimTaskType_TASK_ALLREDUCE,
    SimTaskType_TASK_REDUCESCATTER,
    SimTaskType_TASK_ALLGATHER,
    SimTaskType_TASK_ALLTOALL
  };
  return values;
}

inline const char * const *EnumNamesSimTaskType() {
  static const char * const names[15] = {
    "TASK_FORWARD",
    "TASK_BACKWARD",
    "TASK_COMM",
    "TASK_UPDATE",
    "TASK_BARRIER",
    "TASK_NOMINAL_COMM",
    "TASK_P2P",
    "TASK_SUB_ALLREDUCE",
    "TASK_DP_ALLREDUCE",
    "TASK_TP_ALLREDUCE",
    "TASK_ALLREDUCE",
    "TASK_REDUCESCATTER",
    "TASK_ALLGATHER",
    "TASK_ALLTOALL",
    nullptr
  };
  return names;
}

inline const char *EnumNameSimTaskType(SimTaskType e) {
  if (::flatbuffers::IsOutRange(e, SimTaskType_TASK_FORWARD, SimTaskType_TASK_ALLTOALL)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSimTaskType()[index];
}

enum DeviceType : int16_t {
  DeviceType_DEVICE_COMP_GPU = 0,
  DeviceType_DEVICE_COMP_CPU = 1,
  DeviceType_DEVICE_MEM_SYSTEM = 2,
  DeviceType_DEVICE_MEM_Z_COPY = 3,
  DeviceType_DEVICE_MEM_GPU_FB = 4,
  DeviceType_DEVICE_COMM_MEMBUS_COMM = 5,
  DeviceType_DEVICE_COMM_UPI_IN_COMM = 6,
  DeviceType_DEVICE_COMM_UPI_OUT_COMM = 7,
  DeviceType_DEVICE_COMM_NIC_IN_COMM = 8,
  DeviceType_DEVICE_COMM_NIC_OUT_COMM = 9,
  DeviceType_DEVICE_COMM_PCI_TO_HOST_COMM = 10,
  DeviceType_DEVICE_COMM_PCI_TO_DEV_COMM = 11,
  DeviceType_DEVICE_COMM_NVLINK_COMM = 12,
  DeviceType_DEVICE_COMM_NW_COMM = 13,
  DeviceType_DEVICE_COMM_NW_NOMINAL = 14,
  DeviceType_MIN = DeviceType_DEVICE_COMP_GPU,
  DeviceType_MAX = DeviceType_DEVICE_COMM_NW_NOMINAL
};

inline const DeviceType (&EnumValuesDeviceType())[15] {
  static const DeviceType values[] = {
    DeviceType_DEVICE_COMP_GPU,
    DeviceType_DEVICE_COMP_CPU,
    DeviceType_DEVICE_MEM_SYSTEM,
    DeviceType_DEVICE_MEM_Z_COPY,
    DeviceType_DEVICE_MEM_GPU_FB,
    DeviceType_DEVICE_COMM_MEMBUS_COMM,
    DeviceType_DEVICE_COMM_UPI_IN_COMM,
    DeviceType_DEVICE_COMM_UPI_OUT_COMM,
    DeviceType_DEVICE_COMM_NIC_IN_COMM,
    DeviceType_DEVICE_COMM_NIC_OUT_COMM,
    DeviceType_DEVICE_COMM_PCI_TO_HOST_COMM,
    DeviceType_DEVICE_COMM_PCI_TO_DEV_COMM,
    DeviceType_DEVICE_COMM_NVLINK_COMM,
    DeviceType_DEVICE_COMM_NW_COMM,
    DeviceType_DEVICE_COMM_NW_NOMINAL
  };
  return values;
}

inline const char * const *EnumNamesDeviceType() {
  static const char * const names[16] = {
    "DEVICE_COMP_GPU",
    "DEVICE_COMP_CPU",
    "DEVICE_MEM_SYSTEM",
    "DEVICE_MEM_Z_COPY",
    "DEVICE_MEM_GPU_FB",
    "DEVICE_COMM_MEMBUS_COMM",
    "DEVICE_COMM_UPI_IN_COMM",
    "DEVICE_COMM_UPI_OUT_COMM",
    "DEVICE_COMM_NIC_IN_COMM",
    "DEVICE_COMM_NIC_OUT_COMM",
    "DEVICE_COMM_PCI_TO_HOST_COMM",
    "DEVICE_COMM_PCI_TO_DEV_COMM",
    "DEVICE_COMM_NVLINK_COMM",
    "DEVICE_COMM_NW_COMM",
    "DEVICE_COMM_NW_NOMINAL",
    nullptr
  };
  return names;
}

inline const char *EnumNameDeviceType(DeviceType e) {
  if (::flatbuffers::IsOutRange(e, DeviceType_DEVICE_COMP_GPU, DeviceType_DEVICE_COMM_NW_NOMINAL)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDeviceType()[index];
}

struct Task FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TaskBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_TASKID = 6,
    VT_DEVICEID = 8,
    VT_RUNTIME = 10,
    VT_XFERSIZE = 12,
    VT_COUNTER = 14,
    VT_NEXTTASKS = 16,
    VT_FROM_NODE_IDS = 18,
    VT_TO_NODE_IDS = 20,
    VT_NAME = 22,
    VT_INFO = 24,
    VT_MICRO_BATCH_ID = 26,
    VT_LAYER_ID = 28,
    VT_TARGET_MICRO_BATCH_ID = 30,
    VT_TARGET_LAYER_ID = 32
  };
  FlatBufTaskGraph::SimTaskType type() const {
    return static_cast<FlatBufTaskGraph::SimTaskType>(GetField<int16_t>(VT_TYPE, 0));
  }
  uint64_t taskid() const {
    return GetField<uint64_t>(VT_TASKID, 0);
  }
  uint64_t deviceid() const {
    return GetField<uint64_t>(VT_DEVICEID, 0);
  }
  float runtime() const {
    return GetField<float>(VT_RUNTIME, 0.0f);
  }
  uint64_t xfersize() const {
    return GetField<uint64_t>(VT_XFERSIZE, 0);
  }
  int32_t counter() const {
    return GetField<int32_t>(VT_COUNTER, 0);
  }
  const ::flatbuffers::Vector<uint64_t> *nexttasks() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_NEXTTASKS);
  }
  const ::flatbuffers::Vector<uint64_t> *from_node_ids() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_FROM_NODE_IDS);
  }
  const ::flatbuffers::Vector<uint64_t> *to_node_ids() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_TO_NODE_IDS);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *info() const {
    return GetPointer<const ::flatbuffers::String *>(VT_INFO);
  }
  int32_t micro_batch_id() const {
    return GetField<int32_t>(VT_MICRO_BATCH_ID, 0);
  }
  int32_t layer_id() const {
    return GetField<int32_t>(VT_LAYER_ID, 0);
  }
  int32_t target_micro_batch_id() const {
    return GetField<int32_t>(VT_TARGET_MICRO_BATCH_ID, 0);
  }
  int32_t target_layer_id() const {
    return GetField<int32_t>(VT_TARGET_LAYER_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_TYPE, 2) &&
           VerifyField<uint64_t>(verifier, VT_TASKID, 8) &&
           VerifyField<uint64_t>(verifier, VT_DEVICEID, 8) &&
           VerifyField<float>(verifier, VT_RUNTIME, 4) &&
           VerifyField<uint64_t>(verifier, VT_XFERSIZE, 8) &&
           VerifyField<int32_t>(verifier, VT_COUNTER, 4) &&
           VerifyOffset(verifier, VT_NEXTTASKS) &&
           verifier.VerifyVector(nexttasks()) &&
           VerifyOffset(verifier, VT_FROM_NODE_IDS) &&
           verifier.VerifyVector(from_node_ids()) &&
           VerifyOffset(verifier, VT_TO_NODE_IDS) &&
           verifier.VerifyVector(to_node_ids()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_INFO) &&
           verifier.VerifyString(info()) &&
           VerifyField<int32_t>(verifier, VT_MICRO_BATCH_ID, 4) &&
           VerifyField<int32_t>(verifier, VT_LAYER_ID, 4) &&
           VerifyField<int32_t>(verifier, VT_TARGET_MICRO_BATCH_ID, 4) &&
           VerifyField<int32_t>(verifier, VT_TARGET_LAYER_ID, 4) &&
           verifier.EndTable();
  }
};

struct TaskBuilder {
  typedef Task Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(FlatBufTaskGraph::SimTaskType type) {
    fbb_.AddElement<int16_t>(Task::VT_TYPE, static_cast<int16_t>(type), 0);
  }
  void add_taskid(uint64_t taskid) {
    fbb_.AddElement<uint64_t>(Task::VT_TASKID, taskid, 0);
  }
  void add_deviceid(uint64_t deviceid) {
    fbb_.AddElement<uint64_t>(Task::VT_DEVICEID, deviceid, 0);
  }
  void add_runtime(float runtime) {
    fbb_.AddElement<float>(Task::VT_RUNTIME, runtime, 0.0f);
  }
  void add_xfersize(uint64_t xfersize) {
    fbb_.AddElement<uint64_t>(Task::VT_XFERSIZE, xfersize, 0);
  }
  void add_counter(int32_t counter) {
    fbb_.AddElement<int32_t>(Task::VT_COUNTER, counter, 0);
  }
  void add_nexttasks(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> nexttasks) {
    fbb_.AddOffset(Task::VT_NEXTTASKS, nexttasks);
  }
  void add_from_node_ids(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> from_node_ids) {
    fbb_.AddOffset(Task::VT_FROM_NODE_IDS, from_node_ids);
  }
  void add_to_node_ids(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> to_node_ids) {
    fbb_.AddOffset(Task::VT_TO_NODE_IDS, to_node_ids);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Task::VT_NAME, name);
  }
  void add_info(::flatbuffers::Offset<::flatbuffers::String> info) {
    fbb_.AddOffset(Task::VT_INFO, info);
  }
  void add_micro_batch_id(int32_t micro_batch_id) {
    fbb_.AddElement<int32_t>(Task::VT_MICRO_BATCH_ID, micro_batch_id, 0);
  }
  void add_layer_id(int32_t layer_id) {
    fbb_.AddElement<int32_t>(Task::VT_LAYER_ID, layer_id, 0);
  }
  void add_target_micro_batch_id(int32_t target_micro_batch_id) {
    fbb_.AddElement<int32_t>(Task::VT_TARGET_MICRO_BATCH_ID, target_micro_batch_id, 0);
  }
  void add_target_layer_id(int32_t target_layer_id) {
    fbb_.AddElement<int32_t>(Task::VT_TARGET_LAYER_ID, target_layer_id, 0);
  }
  explicit TaskBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Task> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Task>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Task> CreateTask(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    FlatBufTaskGraph::SimTaskType type = FlatBufTaskGraph::SimTaskType_TASK_FORWARD,
    uint64_t taskid = 0,
    uint64_t deviceid = 0,
    float runtime = 0.0f,
    uint64_t xfersize = 0,
    int32_t counter = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> nexttasks = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> from_node_ids = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> to_node_ids = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> info = 0,
    int32_t micro_batch_id = 0,
    int32_t layer_id = 0,
    int32_t target_micro_batch_id = 0,
    int32_t target_layer_id = 0) {
  TaskBuilder builder_(_fbb);
  builder_.add_xfersize(xfersize);
  builder_.add_deviceid(deviceid);
  builder_.add_taskid(taskid);
  builder_.add_target_layer_id(target_layer_id);
  builder_.add_target_micro_batch_id(target_micro_batch_id);
  builder_.add_layer_id(layer_id);
  builder_.add_micro_batch_id(micro_batch_id);
  builder_.add_info(info);
  builder_.add_name(name);
  builder_.add_to_node_ids(to_node_ids);
  builder_.add_from_node_ids(from_node_ids);
  builder_.add_nexttasks(nexttasks);
  builder_.add_counter(counter);
  builder_.add_runtime(runtime);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Task> CreateTaskDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    FlatBufTaskGraph::SimTaskType type = FlatBufTaskGraph::SimTaskType_TASK_FORWARD,
    uint64_t taskid = 0,
    uint64_t deviceid = 0,
    float runtime = 0.0f,
    uint64_t xfersize = 0,
    int32_t counter = 0,
    const std::vector<uint64_t> *nexttasks = nullptr,
    const std::vector<uint64_t> *from_node_ids = nullptr,
    const std::vector<uint64_t> *to_node_ids = nullptr,
    const char *name = nullptr,
    const char *info = nullptr,
    int32_t micro_batch_id = 0,
    int32_t layer_id = 0,
    int32_t target_micro_batch_id = 0,
    int32_t target_layer_id = 0) {
  auto nexttasks__ = nexttasks ? _fbb.CreateVector<uint64_t>(*nexttasks) : 0;
  auto from_node_ids__ = from_node_ids ? _fbb.CreateVector<uint64_t>(*from_node_ids) : 0;
  auto to_node_ids__ = to_node_ids ? _fbb.CreateVector<uint64_t>(*to_node_ids) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto info__ = info ? _fbb.CreateString(info) : 0;
  return FlatBufTaskGraph::CreateTask(
      _fbb,
      type,
      taskid,
      deviceid,
      runtime,
      xfersize,
      counter,
      nexttasks__,
      from_node_ids__,
      to_node_ids__,
      name__,
      info__,
      micro_batch_id,
      layer_id,
      target_micro_batch_id,
      target_layer_id);
}

struct Device FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DeviceBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_DEVICEID = 6,
    VT_NODEID = 8,
    VT_DEVICEPROPERTY = 10,
    VT_BANDWIDTH = 12
  };
  FlatBufTaskGraph::DeviceType type() const {
    return static_cast<FlatBufTaskGraph::DeviceType>(GetField<int16_t>(VT_TYPE, 0));
  }
  uint64_t deviceid() const {
    return GetField<uint64_t>(VT_DEVICEID, 0);
  }
  uint64_t nodeid() const {
    return GetField<uint64_t>(VT_NODEID, 0);
  }
  uint64_t deviceproperty() const {
    return GetField<uint64_t>(VT_DEVICEPROPERTY, 0);
  }
  uint64_t bandwidth() const {
    return GetField<uint64_t>(VT_BANDWIDTH, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_TYPE, 2) &&
           VerifyField<uint64_t>(verifier, VT_DEVICEID, 8) &&
           VerifyField<uint64_t>(verifier, VT_NODEID, 8) &&
           VerifyField<uint64_t>(verifier, VT_DEVICEPROPERTY, 8) &&
           VerifyField<uint64_t>(verifier, VT_BANDWIDTH, 8) &&
           verifier.EndTable();
  }
};

struct DeviceBuilder {
  typedef Device Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(FlatBufTaskGraph::DeviceType type) {
    fbb_.AddElement<int16_t>(Device::VT_TYPE, static_cast<int16_t>(type), 0);
  }
  void add_deviceid(uint64_t deviceid) {
    fbb_.AddElement<uint64_t>(Device::VT_DEVICEID, deviceid, 0);
  }
  void add_nodeid(uint64_t nodeid) {
    fbb_.AddElement<uint64_t>(Device::VT_NODEID, nodeid, 0);
  }
  void add_deviceproperty(uint64_t deviceproperty) {
    fbb_.AddElement<uint64_t>(Device::VT_DEVICEPROPERTY, deviceproperty, 0);
  }
  void add_bandwidth(uint64_t bandwidth) {
    fbb_.AddElement<uint64_t>(Device::VT_BANDWIDTH, bandwidth, 0);
  }
  explicit DeviceBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Device> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Device>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Device> CreateDevice(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    FlatBufTaskGraph::DeviceType type = FlatBufTaskGraph::DeviceType_DEVICE_COMP_GPU,
    uint64_t deviceid = 0,
    uint64_t nodeid = 0,
    uint64_t deviceproperty = 0,
    uint64_t bandwidth = 0) {
  DeviceBuilder builder_(_fbb);
  builder_.add_bandwidth(bandwidth);
  builder_.add_deviceproperty(deviceproperty);
  builder_.add_nodeid(nodeid);
  builder_.add_deviceid(deviceid);
  builder_.add_type(type);
  return builder_.Finish();
}

struct Operator FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OperatorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OPID = 4,
    VT_TYPE = 6,
    VT_NAME = 8
  };
  uint64_t opid() const {
    return GetField<uint64_t>(VT_OPID, 0);
  }
  uint64_t type() const {
    return GetField<uint64_t>(VT_TYPE, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_OPID, 8) &&
           VerifyField<uint64_t>(verifier, VT_TYPE, 8) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct OperatorBuilder {
  typedef Operator Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_opid(uint64_t opid) {
    fbb_.AddElement<uint64_t>(Operator::VT_OPID, opid, 0);
  }
  void add_type(uint64_t type) {
    fbb_.AddElement<uint64_t>(Operator::VT_TYPE, type, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Operator::VT_NAME, name);
  }
  explicit OperatorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Operator> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Operator>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Operator> CreateOperator(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t opid = 0,
    uint64_t type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  OperatorBuilder builder_(_fbb);
  builder_.add_type(type);
  builder_.add_opid(opid);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Operator> CreateOperatorDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t opid = 0,
    uint64_t type = 0,
    const char *name = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return FlatBufTaskGraph::CreateOperator(
      _fbb,
      opid,
      type,
      name__);
}

struct TaskGraph FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TaskGraphBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NGPUPERNODE = 4,
    VT_NNODE = 6,
    VT_INTERGPUBW = 8,
    VT_DRAMBW = 10,
    VT_NETBW = 12,
    VT_OPS = 14,
    VT_TASKS = 16,
    VT_DEVICES = 18,
    VT_DP_DEGREE = 20,
    VT_TP_DEGREE = 22,
    VT_PP_DEGREE = 24,
    VT_EP_DEGREE = 26
  };
  uint32_t ngpupernode() const {
    return GetField<uint32_t>(VT_NGPUPERNODE, 0);
  }
  uint32_t nnode() const {
    return GetField<uint32_t>(VT_NNODE, 0);
  }
  float intergpubw() const {
    return GetField<float>(VT_INTERGPUBW, 0.0f);
  }
  float drambw() const {
    return GetField<float>(VT_DRAMBW, 0.0f);
  }
  float netbw() const {
    return GetField<float>(VT_NETBW, 0.0f);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<FlatBufTaskGraph::Operator>> *ops() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<FlatBufTaskGraph::Operator>> *>(VT_OPS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<FlatBufTaskGraph::Task>> *tasks() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<FlatBufTaskGraph::Task>> *>(VT_TASKS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<FlatBufTaskGraph::Device>> *devices() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<FlatBufTaskGraph::Device>> *>(VT_DEVICES);
  }
  uint32_t dp_degree() const {
    return GetField<uint32_t>(VT_DP_DEGREE, 0);
  }
  uint32_t tp_degree() const {
    return GetField<uint32_t>(VT_TP_DEGREE, 0);
  }
  uint32_t pp_degree() const {
    return GetField<uint32_t>(VT_PP_DEGREE, 0);
  }
  uint32_t ep_degree() const {
    return GetField<uint32_t>(VT_EP_DEGREE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_NGPUPERNODE, 4) &&
           VerifyField<uint32_t>(verifier, VT_NNODE, 4) &&
           VerifyField<float>(verifier, VT_INTERGPUBW, 4) &&
           VerifyField<float>(verifier, VT_DRAMBW, 4) &&
           VerifyField<float>(verifier, VT_NETBW, 4) &&
           VerifyOffset(verifier, VT_OPS) &&
           verifier.VerifyVector(ops()) &&
           verifier.VerifyVectorOfTables(ops()) &&
           VerifyOffset(verifier, VT_TASKS) &&
           verifier.VerifyVector(tasks()) &&
           verifier.VerifyVectorOfTables(tasks()) &&
           VerifyOffset(verifier, VT_DEVICES) &&
           verifier.VerifyVector(devices()) &&
           verifier.VerifyVectorOfTables(devices()) &&
           VerifyField<uint32_t>(verifier, VT_DP_DEGREE, 4) &&
           VerifyField<uint32_t>(verifier, VT_TP_DEGREE, 4) &&
           VerifyField<uint32_t>(verifier, VT_PP_DEGREE, 4) &&
           VerifyField<uint32_t>(verifier, VT_EP_DEGREE, 4) &&
           verifier.EndTable();
  }
};

struct TaskGraphBuilder {
  typedef TaskGraph Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ngpupernode(uint32_t ngpupernode) {
    fbb_.AddElement<uint32_t>(TaskGraph::VT_NGPUPERNODE, ngpupernode, 0);
  }
  void add_nnode(uint32_t nnode) {
    fbb_.AddElement<uint32_t>(TaskGraph::VT_NNODE, nnode, 0);
  }
  void add_intergpubw(float intergpubw) {
    fbb_.AddElement<float>(TaskGraph::VT_INTERGPUBW, intergpubw, 0.0f);
  }
  void add_drambw(float drambw) {
    fbb_.AddElement<float>(TaskGraph::VT_DRAMBW, drambw, 0.0f);
  }
  void add_netbw(float netbw) {
    fbb_.AddElement<float>(TaskGraph::VT_NETBW, netbw, 0.0f);
  }
  void add_ops(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FlatBufTaskGraph::Operator>>> ops) {
    fbb_.AddOffset(TaskGraph::VT_OPS, ops);
  }
  void add_tasks(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FlatBufTaskGraph::Task>>> tasks) {
    fbb_.AddOffset(TaskGraph::VT_TASKS, tasks);
  }
  void add_devices(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FlatBufTaskGraph::Device>>> devices) {
    fbb_.AddOffset(TaskGraph::VT_DEVICES, devices);
  }
  void add_dp_degree(uint32_t dp_degree) {
    fbb_.AddElement<uint32_t>(TaskGraph::VT_DP_DEGREE, dp_degree, 0);
  }
  void add_tp_degree(uint32_t tp_degree) {
    fbb_.AddElement<uint32_t>(TaskGraph::VT_TP_DEGREE, tp_degree, 0);
  }
  void add_pp_degree(uint32_t pp_degree) {
    fbb_.AddElement<uint32_t>(TaskGraph::VT_PP_DEGREE, pp_degree, 0);
  }
  void add_ep_degree(uint32_t ep_degree) {
    fbb_.AddElement<uint32_t>(TaskGraph::VT_EP_DEGREE, ep_degree, 0);
  }
  explicit TaskGraphBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TaskGraph> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TaskGraph>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TaskGraph> CreateTaskGraph(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t ngpupernode = 0,
    uint32_t nnode = 0,
    float intergpubw = 0.0f,
    float drambw = 0.0f,
    float netbw = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FlatBufTaskGraph::Operator>>> ops = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FlatBufTaskGraph::Task>>> tasks = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<FlatBufTaskGraph::Device>>> devices = 0,
    uint32_t dp_degree = 0,
    uint32_t tp_degree = 0,
    uint32_t pp_degree = 0,
    uint32_t ep_degree = 0) {
  TaskGraphBuilder builder_(_fbb);
  builder_.add_ep_degree(ep_degree);
  builder_.add_pp_degree(pp_degree);
  builder_.add_tp_degree(tp_degree);
  builder_.add_dp_degree(dp_degree);
  builder_.add_devices(devices);
  builder_.add_tasks(tasks);
  builder_.add_ops(ops);
  builder_.add_netbw(netbw);
  builder_.add_drambw(drambw);
  builder_.add_intergpubw(intergpubw);
  builder_.add_nnode(nnode);
  builder_.add_ngpupernode(ngpupernode);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TaskGraph> CreateTaskGraphDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t ngpupernode = 0,
    uint32_t nnode = 0,
    float intergpubw = 0.0f,
    float drambw = 0.0f,
    float netbw = 0.0f,
    const std::vector<::flatbuffers::Offset<FlatBufTaskGraph::Operator>> *ops = nullptr,
    const std::vector<::flatbuffers::Offset<FlatBufTaskGraph::Task>> *tasks = nullptr,
    const std::vector<::flatbuffers::Offset<FlatBufTaskGraph::Device>> *devices = nullptr,
    uint32_t dp_degree = 0,
    uint32_t tp_degree = 0,
    uint32_t pp_degree = 0,
    uint32_t ep_degree = 0) {
  auto ops__ = ops ? _fbb.CreateVector<::flatbuffers::Offset<FlatBufTaskGraph::Operator>>(*ops) : 0;
  auto tasks__ = tasks ? _fbb.CreateVector<::flatbuffers::Offset<FlatBufTaskGraph::Task>>(*tasks) : 0;
  auto devices__ = devices ? _fbb.CreateVector<::flatbuffers::Offset<FlatBufTaskGraph::Device>>(*devices) : 0;
  return FlatBufTaskGraph::CreateTaskGraph(
      _fbb,
      ngpupernode,
      nnode,
      intergpubw,
      drambw,
      netbw,
      ops__,
      tasks__,
      devices__,
      dp_degree,
      tp_degree,
      pp_degree,
      ep_degree);
}

}  // namespace FlatBufTaskGraph

#endif  // FLATBUFFERS_GENERATED_TASKGRAPH_FLATBUFTASKGRAPH_H_
